---
apiVersion: v1
kind: ReplicationController
metadata:
  name: be-rc
  labels:
    type: be-type
spec:
  replicas: 2
  template:
    metadata:
      labels:
        type: be-type
    spec:
      containers:
      - name: be-container
        image: gcr.io/testkube-187517/be
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          protocol: TCP
        env:
        - name: USER_VAR
          value: important information
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
