kind: Service
apiVersion: v1
metadata:
  name: dogopark-backend
spec:
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    role: backend
    app: backend
  tyoe: LoadBalancer
