kind: Service
apiVersion: v1
metadata:
  name: dogpark-backend
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: dogpark
    role: backend